# Generated by Django 4.2.2 on 2023-06-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product',
        ),
    ]
