# Generated by Django 4.2.2 on 2023-06-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0004_rename_products_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
